[package]
name = "atop"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
mach2 = "0.5"
core-foundation = "0.10"
core-foundation-sys = "0.8"
